### ISSUE TITLE
Expected IP, Mask and GW are not displayed

### ISSUE THREAD

**Issue by pipiche38** [fairecasoimeme/ZiGate-Ethernet#3]
![Screenshot 2021-08-22 at 11 39 35](https://user-images.githubusercontent.com/8291674/130351702-b8eb7c57-8f13-4130-a51f-308f8ddde6b8.png)

**Comment by fairecasoimeme** [comment]
fixed https://github.com/fairecasoimeme/ZiGate-Ethernet/commit/b20337b6c20285d353c4cc1a796e39c410970719
